apiVersion: apps/v1
kind: Deployment
metadata:
  name: qa-board
  labels:
    app: qa-board
  namespace: default
spec:
  selector:
    matchLabels:
      app: qa-board
  replicas: 1
  template:
    metadata:
      labels:
        app: qa-board
    spec:
      containers:
      - name: qa-board
        image: matkimchi/probono_qa_board:39875
        imagePullPolicy: Always
        ports:
        - containerPort: 8090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot
  labels:
    app: chatbot
  namespace: default
spec:
  selector:
    matchLabels:
      app: chatbot
  replicas: 1
  template:
    metadata:
      labels:
        app: chatbot
    spec:
      containers:
      - name: chatbot
<<<<<<< HEAD
        image: matkimchi/probono_chatbot:1410
=======
        image: matkimchi/probono_chatbot:140
>>>>>>> 35cc554 (test)
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: announcement
  labels:
    app: announcement
  namespace: default
spec:
  selector:
    matchLabels:
      app: announcement
  replicas: 1
  template:
    metadata:
      labels:
        app: announcement
    spec:
      containers:
      - name: announcement
        image: matkimchi/probono_announcement:3
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: login
  labels:
    app: login
  namespace: default
spec:
  selector:
    matchLabels:
      app: login
  replicas: 1
  template:
    metadata:
      labels:
        app: login
    spec:
      containers:
      - name: login
        image: matkimchi/probono_login:5
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: qa-service 
  labels:
    app: qa-board
spec:
  selector:
    app: qa-board
  ports:
  - port: 8090
    name: http
---
apiVersion: v1
kind: Service
metadata:
  name: chatbot-service 
  labels:
    app: chatbot
spec:
  selector:
    app: chatbot
  ports:
  - port: 8000
    name: http

---
apiVersion: v1
kind: Service
metadata:
  name: announcement-service 
  labels:
    app: announcement
spec:
  selector:
    app: announcement
  ports:
  - port: 8080
    name: http

---
apiVersion: v1
kind: Service
metadata:
  name: login-service 
  labels:
    app: login
spec:
  selector:
    app: login
  ports:
  - port: 8080
    name: http

    