apiVersion: v1
kind: Secret
metadata:
  name: my-private-https-repo
  namespace: argocd
  labels:   
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/probono-24PF012/ruddy-Infra.git
